# flask.yaml (Deployment and Service)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask-app
          image: sirishak83/2-tier-flaskapp:latest
          ports:
            - containerPort: 5000
          env:
            # --- MATCHES YOUR DOCKER-COMPOSE ---
            - name: MYSQL_HOST
              value: mysql-service # The name of the MySQL Service (Kubernetes Network)
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: root
            - name: MYSQL_DB
              value: devops
            # -----------------------------------

            ---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 80 # External access port
      targetPort: 5000 # The port your Flask app is running on inside the container
  
  # Use LoadBalancer for cloud K8s (EKS, GKE, AKS)
  # Use NodePort if running on a local cluster (Minikube, Kind)
  type: LoadBalancer