apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce # Only one node can mount it
  resources:
    requests:
      storage: 1Gi # Request 1 Gigabyte of storage
